// react-app/src/components/HeaderBarBrand.js
import React from 'react';
import {NavLink} from 'react-router-dom';

const HeaderBarBrand = () => (
  <div className="navbar-brand">
    <a
      className="navbar-item"
      href="https://reactjs.org/"
      target="_blank"
      rel="noopener noreferrer"
    >
      <i className="fab js-logo fa-react fa-2x" aria-hidden="true" />
    </a>
    <NavLink to="/" className="navbar-item nav-home">
      <span className="brand-first">MY</span>
      <span className="brand-second">SHOPPING</span>
      <span className="brand-third">LIST</span>
    </NavLink>
  </div>
);

export default HeaderBarBrand;

// angular-app/src/app/core/components/header-bar-brand.component.ts
import {Component} from '@angular/core';

@Component({
  selector: 'app-header-bar-brand',
  template: `
    <div class="navbar-brand">
      <a
        class="navbar-item"
        href="https://angular.io/"
        target="_blank"
        rel="noopener noreferrer"
      >
        <i class="fab js-logo fa-angular fa-2x" aria-hidden="true"></i>
      </a>
      <a class="navbar-item nav-home" router-link="/">
        <span class="brand-first">MY</span>
        <span class="brand-second">SHOPPING</span>
        <span class="brand-third">LIST</span>
      </a>
    </div>
  `,
})
export class HeaderBarBrandComponent {}
