// angular-app/src/app/shared/list-header.component.ts
import {Component, EventEmitter, Input, OnInit, Output} from '@angular/core';

@Component({
  selector: 'app-list-header',
  template: `
    <div class="content-title-group">
      <a router-link="/">
        <h2 class="title">{{ title }}</h2>
      </a>
      <button
        class="button refresh-button"
        (click)="handleRefresh()"
        aria-label="refresh"
      >
        <i class="fas fa-sync" aria-hidden="true"></i>
      </button>
    </div>
  `,
})
export class ListHeaderComponent implements OnInit {
  @Input() title: string;
  @Output() refresh = new EventEmitter();

  ngOnInit() {}

  handleRefresh() {
    this.refresh.emit();
  }
}

// react-app/src/components/ListHeader.js
import React from 'react';
import {NavLink} from 'react-router-dom';

const ListHeader = ({ title, handleRefresh, routePath }) => {
  return (
    <div className="content-title-group">
      <NavLink to={routePath}>
        <h2 className="title">{title}</h2>
      </NavLink>
      <button
        className="button refresh-button"
        onClick={handleRefresh}
        aria-label="refresh"
      >
        <i className="fas fa-sync" aria-hidden="true" />
      </button>
    </div>
  );
};

export default ListHeader;
