// angular-app/src/app/products/product-list.component.ts
import {ChangeDetectionStrategy, Component, Input} from '@angular/core';
import {Product} from '../core';

@Component({
  selector: 'app-product-list',
  template: `
    <div *ngIf="!products?.length">
      Loading data ...
    </div>
    <ul class="list">
      <li
        role="presentation"
        *ngFor="let product of products; trackBy: trackByProduct; let i = index"
      >
        <div class="card">
          <app-card-content
            [name]="product.name"
            [description]="product.description"
          ></app-card-content>
        </div>
      </li>
    </ul>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProductListComponent {
  @Input() products: Product[];

  trackByProduct(index: number, product: Product): number {
    return product.id;
  }
}

// react-app/src/products/ProductList.js
import React from 'react';
import {withRouter} from 'react-router';

import {CardContent} from '../components';

function ProductList({products}) {
  return (
    <div>
      {products.length === 0 && <div>Loading data ...</div>}
      <ul className="list">
        {products.map((product) => (
          <li key={product.id} role="presentation">
            <div className="card">
              <CardContent
                name={product.name}
                description={product.description}
              />
            </div>
          </li>
        ))}
      </ul>
    </div>
  );
}

export default withRouter(ProductList);
