// react-app/src/products/Products.js
import React, {useEffect} from 'react';
import {Route, Switch} from 'react-router-dom';

import {ListHeader} from '../components';
import ProductList from './ProductList';
import useProducts from './useProducts';

function Products() {
  const { getProducts, products } = useProducts();

  useEffect(() => {
    getProducts();
  }, [getProducts]);

  function handleRefresh() {
    getProducts();
  }

  return (
    <div className="content-container">
      <ListHeader
        title="Products"
        handleRefresh={handleRefresh}
        routePath="/products"
      />
      <div className="columns is-multiline is-variable">
        <div className="column is-8">
          <Switch>
            <Route
              exact
              path="/products"
              component={() => <ProductList products={products} />}
            />
          </Switch>
        </div>
      </div>
    </div>
  );
}

export default Products;

// vue-app/src/views/products/products.vue
<script>
import {mapActions, mapGetters} from 'vuex';
import ListHeader from '@/components/list-header.vue';
import ProductList from './product-list.vue';

export default {
  name: 'Products',
  data() {
    return {
      routePath: '/products',
      title: 'Products',
    };
  },
  components: {
    ListHeader,
    ProductList,
  },
  created() {
    this.getProductsAction();
  },
  computed: {
    ...mapGetters('products', { products: 'products' }),
  },
  methods: {
    ...mapActions('products', ['getProductsAction']),
    getProducts() {
      this.getProductsAction();
    },
  },
};
</script>

<template>
  <div class="content-container">
    <ListHeader
      :title="title"
      @refresh="getProducts"
      :routePath="routePath"
    ></ListHeader>
    <div class="columns is-multiline is-variable">
      <div class="column is-8" v-if="products">
        <ProductList :products="products"></ProductList>
      </div>
    </div>
  </div>
</template>
